In [ ]:
pip install dash plotly flask flask-socketio pandas

In [1]:
pip install geojson

Requirement already satisfied: geojson in c:\users\usuario\appdata\local\programs\python\python312\lib\site-packages (3.2.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import dash
from dash import dcc, html
import plotly.express as px
import geojson
import pandas as pd
from flask import Flask, render_template
import json

# Cargar datos GeoJSON (ajusta la ruta si es necesario)
with open('MUERTO.geojson') as f:
    geojson_data = json.load(f)

# Convertir el GeoJSON a un DataFrame
features = geojson_data['features']

# Extraer coordenadas y propiedades para el DataFrame
data = []
for feature in features:
    coords = feature['geometry']['coordinates']
    properties = feature['properties']
    data.append({
        'longitude': coords[0],
        'latitude': coords[1],
        'Accidente': properties.get('Accidente', 'Desconocido'),
        'Fecha': properties.get('Fecha', 'Desconocido'),
    })

df = pd.DataFrame(data)

# Crear una instancia de Flask
server = Flask(__name__)

# Crear una instancia de Dash
app = dash.Dash(__name__, server=server, routes_pathname_prefix='/dash/')

# Crear un gr√°fico inicial con Plotly
fig = px.scatter_mapbox(
    df,  # Usamos el DataFrame en lugar del geojson directamente
    lat="latitude",  # Usamos las coordenadas extra√≠das
    lon="longitude",  # Usamos las coordenadas extra√≠das
    color="Accidente",  # Coloreamos seg√∫n el tipo de accidente
    hover_name="Fecha",  # Muestra la fecha al pasar el rat√≥n
    title="Accidentes de Tr√°fico en Bogot√°",
    labels={"Accidente": "Tipo de Accidente"},
)

# Configuraci√≥n del mapa
fig.update_layout(
    mapbox_style="carto-positron",
    mapbox_zoom=10,
    mapbox_center={"lat": 4.60971, "lon": -74.08175},  # Centro de Bogot√°
)

# Layout de Dash
app.layout = html.Div([
    html.H1("Dashboard de Accidentes de Tr√°fico en Bogot√°"),
    dcc.Graph(id="mapa", figure=fig),
])

# Ruta principal para servir la plantilla HTML
@server.route('/')
def index():
    return render_template('index.html')

# Ejecutar el servidor
if __name__ == '__main__':
    server.run(debug=True)

C:\Users\Usuario\AppData\Local\Temp\ipykernel_18684\1007294173.py:37: DeprecationWarning:

*scatter_mapbox* is deprecated! Use *scatter_map* instead. Learn more at: https://plotly.com/python/mapbox-to-maplibre/

 * Serving Flask app '__main__'
 * Debug mode: on

WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
 * Restarting with stat

SystemExit: 1

C:\Users\Usuario\AppData\Roaming\Python\Python312\site-packages\IPython\core\interactiveshell.py:3587: UserWarning:

To exit: use 'exit', 'quit', or Ctrl-D.

In [ ]:
df = pd.DataFrame(data)
df

      longitude  latitude    Accidente        Fecha
0    -74.114493  4.588493  Desconocido  Desconocido
1    -74.115042  4.576468  Desconocido  Desconocido
2    -74.143451  4.619175  Desconocido  Desconocido
3    -74.114708  4.627895  Desconocido  Desconocido
4    -74.065947  4.641667  Desconocido  Desconocido
...         ...       ...          ...          ...
8543 -74.094066  4.575375  Desconocido  Desconocido
8544 -74.071338  4.610824  Desconocido  Desconocido
8545 -74.137796  4.707225  Desconocido  Desconocido
8546 -74.161463  4.607957  Desconocido  Desconocido
8547 -74.084033  4.548287  Desconocido  Desconocido

[8548 rows x 4 columns]

In [ ]:

# üìä Gr√°fico 2: N√∫mero total de fallecidos por g√©nero
df_muertes = df[df["Muerte"] == 1]  # Filtrar solo fallecidos
fig_muertes = px.bar(
    df_muertes["Genero"].value_counts().reset_index(),
    x="index", y="Genero",
    labels={"index": "G√©nero", "Genero": "N√∫mero de Fallecidos"},
    title="N√∫mero de Fallecidos por G√©nero",
    color="index"
)

app.layout = html.Div(
    style={'backgroundColor': '#121212', 'color': 'white', 'textAlign': 'center'},
    children=[
        html.H1("Mapa de Accidentes de Tr√°fico en Bogot√°", style={'color': '#00ff99'}),
        dcc.Graph(id="mapa", figure=fig_mapa),
        html.H2("An√°lisis de Accidentes por G√©nero", style={'color': '#00ff99'}),
        dcc.Graph(id="grafico-muertes", figure=fig_muertes)
    ]
)

# Ruta principal para servir la plantilla HTML
@server.route('/')
def index():
    return render_template('index.html')

# Ejecutar el servidor
if __name__ == '__main__':
    server.run(debug=True)

In [14]:
df = pd.DataFrame(data)
df

      longitude  latitude    Accidente        Fecha
0    -74.114493  4.588493  Desconocido  Desconocido
1    -74.115042  4.576468  Desconocido  Desconocido
2    -74.143451  4.619175  Desconocido  Desconocido
3    -74.114708  4.627895  Desconocido  Desconocido
4    -74.065947  4.641667  Desconocido  Desconocido
...         ...       ...          ...          ...
8543 -74.094066  4.575375  Desconocido  Desconocido
8544 -74.071338  4.610824  Desconocido  Desconocido
8545 -74.137796  4.707225  Desconocido  Desconocido
8546 -74.161463  4.607957  Desconocido  Desconocido
8547 -74.084033  4.548287  Desconocido  Desconocido

[8548 rows x 4 columns]

In [16]:
df = pd.DataFrame(data) 
df

      longitude  latitude    Accidente        Fecha
0    -74.114493  4.588493  Desconocido  Desconocido
1    -74.115042  4.576468  Desconocido  Desconocido
2    -74.143451  4.619175  Desconocido  Desconocido
3    -74.114708  4.627895  Desconocido  Desconocido
4    -74.065947  4.641667  Desconocido  Desconocido
...         ...       ...          ...          ...
8543 -74.094066  4.575375  Desconocido  Desconocido
8544 -74.071338  4.610824  Desconocido  Desconocido
8545 -74.137796  4.707225  Desconocido  Desconocido
8546 -74.161463  4.607957  Desconocido  Desconocido
8547 -74.084033  4.548287  Desconocido  Desconocido

[8548 rows x 4 columns]